disable_existing_loggers = false
version = 1

[formatters]

  [formatters.complex]
  datefmt = "%Y-%m-%d %H:%M:%S"
  format = "[%(asctime)s - %(levelname)s] - <PID %(process)d:%(processName)s> %(name)s.%(funcName)s() : %(message)s"

  [formatters.simple]
  datefmt = "%Y-%m-%d %H:%M:%S"
  format = "[%(asctime)s - %(levelname)s] - %(name)s:%(lineno)d : %(message)s"


[handlers]

  [handlers.console]
  class = "logging.StreamHandler"
  formatter = "simple"
  level = "DEBUG"

  [handlers.info_file_handler]
  backupCount = 3
  class = "logging.handlers.RotatingFileHandler"
  encoding = "utf8"
  filename = "logs/info.log"
  formatter = "complex"
  level = "INFO"
  maxBytes = 10485760

  [handlers.error_file_handler]
  backupCount = 3
  class = "logging.handlers.RotatingFileHandler"
  encoding = "utf8"
  filename = "logs/errors.log"
  formatter = "complex"
  level = "ERROR"
  maxBytes = 10485760

[loggers]

  [loggers.interface]
  handlers = ["console", "error_file_handler"]
  level = "WARNING"
  propagate = false

  [loggers.model]
  handlers = ["console", "error_file_handler", "info_file_handler"]
  level = "WARNING"
  propagate = false

  [loggers.misc]
  handlers = ["console", "error_file_handler", "info_file_handler"]
  level = "WARNING"
  propagate = false

  [loggers.stats]
  handlers = ["error_file_handler", "info_file_handler"]
  level = "WARNING"
  propagate = false

[root]
handlers = ["console", "error_file_handler", "info_file_handler"]
formatter = "simple"
level = "INFO"