[tool.poetry]
name = "occuspytial"
version = "0.1.0"
description = "'A package for bayesian analysis of spatial occupancy models'"
authors = ["Zolisa Bleki"]
license = "BSD-3-Clause"
readme = 'README.md'
repository = "https://github.com/zoj613/OccuSpytial/"
keywords = [
    'spatial statistics',
    'spatial data analysis',
    'occupancy modeling',
    'occupancy prediction'
]
include = ["occuspytial/**/.c"]
build = "build.py"

[tool.poetry.dependencies]
python = "3.6.*"
beautifultable = "0.7.0"
pypolyagamma = "^1.2"
matplotlib = "3.1.0"
scipy = "0.19.0"
joblib = "^0.14.0"
scikit-sparse = {version = "*", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
scikit-sparse = ["scikit-sparse"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
