# adapted from:
# https://gist.github.com/jonatasbaldin/b0eba2ac8ee887ca27ee811697d4d73b#file-poetry_and_circleci-yml
version: 2


jobs:
  build-test-lint:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      # if the text key `deps-{{ checksum "pyproject.toml" }}` changes (and it WILL change everytime poetry.lock is updated since we rely on its checksum)
      # and pyproject.toml is updated every time we add a new dependency to our project
      - restore_cache:
          keys:
            - deps-{{ checksum "pyproject.toml" }}
      # Install the dependencies
      - run:
          name: Install Dependencies
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            curl -#SLo pandoc.deb https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb
            sudo dpkg -i pandoc.deb
            poetry install --no-root
            poetry run cythonize occuspytial/*.pyx
            poetry install -E docs
      # If you don't install anything new, this folder won't change and the cache will be effective
      - save_cache:
          key: deps-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      # And send our coverage somewhere, in this case, coveralls
      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run pytest -v --cov=occuspytial occuspytial/ --cov-report=html
            poetry run codecov --token $CODECOV_TOKEN
      # build docs
      - run:
          name: Build docs
          command: |
            cd docs
            poetry run make html
      # run style checks
      - run:
          name: linting
          command: |
            poetry run pre-commit run --all-files


workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-test-lint
